development:
  adapter: postgresql
  database: heygovote_development
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: heygovote_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: heygovote_production
  pool: 5
  timeout: 5000
